In [1]:
import numpy as np
import random

In [15]:
A1 = np.random.random((5, 5))
A1, np.linalg.det(A1), np.linalg.matrix_rank(A1), np.linalg.eigvals(A1)

(array([[0.20335378, 0.06961338, 0.23792651, 0.77938675, 0.14815512],
        [0.03880515, 0.46323401, 0.45443783, 0.95066941, 0.94759771],
        [0.69089979, 0.33234087, 0.95492771, 0.96522274, 0.55257711],
        [0.06987275, 0.69125994, 0.21849881, 0.99179076, 0.6676539 ],
        [0.48575939, 0.79918544, 0.57487856, 0.52186194, 0.51559113]]),
 -0.0010309097326475375,
 5,
 array([ 2.76593914+0.j        ,  0.39945658+0.36934541j,
         0.39945658-0.36934541j, -0.43882452+0.j        ,
         0.00286961+0.j        ]))

In [16]:
A1_t = np.transpose(A1)
A1_t, np.linalg.det(A1_t), np.linalg.matrix_rank(A1_t), np.linalg.eigvals(A1_t)

(array([[0.20335378, 0.03880515, 0.69089979, 0.06987275, 0.48575939],
        [0.06961338, 0.46323401, 0.33234087, 0.69125994, 0.79918544],
        [0.23792651, 0.45443783, 0.95492771, 0.21849881, 0.57487856],
        [0.77938675, 0.95066941, 0.96522274, 0.99179076, 0.52186194],
        [0.14815512, 0.94759771, 0.55257711, 0.6676539 , 0.51559113]]),
 -0.0010309097326475182,
 5,
 array([ 2.76593914+0.j        ,  0.39945658+0.36934541j,
         0.39945658-0.36934541j,  0.00286961+0.j        ,
        -0.43882452+0.j        ]))

определитель и ранг транспонированной матрицы не изменились, в собственных значениях 4 и 5 поменялись местами

In [17]:
A1_i = np.linalg.inv(A1)
A1_i, np.linalg.det(A1_i), np.linalg.matrix_rank(A1_i), np.linalg.eigvals(A1_i)

(array([[ 170.75078885,   98.72826701, -128.60177821, -172.26424646,
          130.38046568],
        [ -52.77348306,  -31.45259494,   39.17624422,   53.94875605,
          -38.87561943],
        [-153.87455594,  -89.04703746,  116.83065164,  154.02985836,
         -116.79508035],
        [ -11.34726247,   -7.70947402,    9.48925693,   13.37020549,
          -10.05366607],
        [ 103.98334273,   62.82650307,  -79.43325654, -106.59987693,
           79.76263651]]),
 -970.0170328510064,
 5,
 array([348.47976307+0.j        ,  -2.27881523+0.j        ,
          1.34959942+1.24786616j,   1.34959942-1.24786616j,
          0.36154085+0.j        ]))

получили обратный определитель, тот же ранг, новые собственные значения

In [18]:
A2 = np.eye(4)*np.random.random((4, 4))
A2, np.linalg.det(A2), np.linalg.matrix_rank(A2), np.linalg.eigvals(A2)

(array([[0.66895213, 0.        , 0.        , 0.        ],
        [0.        , 0.40621599, 0.        , 0.        ],
        [0.        , 0.        , 0.92687189, 0.        ],
        [0.        , 0.        , 0.        , 0.60223185]]),
 0.15168250393830598,
 4,
 array([0.66895213, 0.40621599, 0.92687189, 0.60223185]))

In [20]:
A3 = np.zeros((3, 3))
A3, np.linalg.det(A3), np.linalg.matrix_rank(A3), np.linalg.eigvals(A3)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 0.0,
 0,
 array([0., 0., 0.]))